version: '3'

services:
  electrs:
    image: romanzeyde/electrs
    environment:
    expose:
      - "50001"
      - "50002"
    volumes:
      - "electrs_datadir:/home/user"
      - "bitcoin_datadir:/root/.bitcoin"

  btcpayserver:
      environment:
          BTCPAY_EXTERNALSERVICES: "Electrs:${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}${BTCPAY_ROOTPATH:-/}electrs"
volumes:
  bitcoin_datadir:
  electrs_datadir: