version: "3"

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        txindex=1
        rpcauth=dojo:7d8ee47c089e6072635f82b34796e878$$13649d99453ccdf78e85007286422599c00e6953289f41bf8e92961076ba14db
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
  dojo-db:
    container_name: dojo-db
    restart: on-failure
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: dojo
      MYSQL_DATABASE: dojo
      MYSQL_USER: dojo
      MYSQL_PASSWORD: dojo
    expose:
      - "3306"
    volumes:
      - "dojo_mariadb_datadir:/var/lib/mysql"
  dojo:
    container_name: dojo
    restart: on-failure
    image: btcpayserver/dojo:1.3.0
    expose:
      - "8080"
      - "8081"
      - "8082"
    volumes:
      - "dojo_datadir:/data"
    environment:
      COMMON_BTC_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BITCOIND_RPC_USER: dojorpc
      BITCOIND_RPC_PASSWORD: dojorpcpassword
      BITCOIND_RPC_PORT: 43782
      BITCOIND_IP: bitcoind
      BITCOIND_ZMQ_RAWTXS: 28333
      BITCOIND_ZMQ_BLK_HASH: 28332

      MYSQL_DATABASE: dojo
      MYSQL_ROOT_PASSWORD: dojo
      MYSQL_USER: dojo
      MYSQL_PASSWORD: dojo
      
      NODE_ACTIVE_INDEXER: local_bitcoind
      NODE_FEE_TYPE: ECONOMICAL
      NODE_GAP_EXTERNAL: 100
      NODE_GAP_INTERNAL: 100
      NODE_ADDR_FILTER_THRESHOLD: 1000
      NODE_URL_OXT_API: https://api.oxt.me
      NODE_URL_ESPLORA_API: https://blockstream.info/testnet
      NODE_ADDR_DERIVATION_MIN_CHILD: 2
      NODE_ADDR_DERIVATION_MAX_CHILD: 2
      NODE_ADDR_DERIVATION_THRESHOLD: 10
      NODE_TXS_SCHED_MAX_ENTRIES: 10
      NODE_TXS_SCHED_MAX_DELTA_HEIGHT: 18

      NODE_JWT_ACCESS_EXPIRES: 900
      NODE_JWT_REFRESH_EXPIRES: 7200

      NODE_PREFIX_STATUS: status
      NODE_PREFIX_SUPPORT: support
      NODE_PREFIX_STATUS_PUSHTX: status
      
      NODE_API_KEY: myApiKey
      NODE_ADMIN_KEY: myAdminKey
      NODE_JWT_SECRET: myJwtSecret
      
volumes:
  dojo_mariadb_datadir:
incompatible:
  - pruning
