version: "3"

services:
  postgres:
    restart: unless-stopped
    image:  postgres:9.6.5
    volumes:
      - "postgres_datadir:/var/lib/postgresql/data"
  btcpayserver:
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
    links:
      - postgres

volumes:
    postgres_datadir: